# Generated by Django 5.0.7 on 2024-09-06 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_alter_customuser_is_staff_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="stripe_customer_id",
        ),
    ]
