# Generated by Django 5.0.7 on 2024-09-12 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_remove_customuser_stripe_customer_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="instructor",
            name="profile_picture",
            field=models.ImageField(blank=True, upload_to="images/"),
        ),
    ]
