# Generated by Django 5.0.7 on 2024-09-16 07:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0006_alter_instructor_profile_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="instructor",
            name="profile_picture",
            field=models.URLField(),
        ),
    ]
