# Generated by Django 5.0.7 on 2024-11-06 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_alter_instructor_profile_picture"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="referral_code",
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
    ]
