# Generated by Django 5.0.7 on 2025-09-26 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_subscriber"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscriber",
            name="end_date",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="subscriber",
            name="start_date",
            field=models.DateTimeField(),
        ),
    ]
