# Generated by Django 5.0.7 on 2024-09-06 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="price",
        ),
    ]
