# Generated by Django 5.0.7 on 2024-09-10 17:59

import cloudinary_storage.storage
import cloudinary_storage.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0002_remove_course_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="featured_image",
            field=models.ImageField(blank=True, upload_to="images/"),
        ),
        migrations.AlterField(
            model_name="video",
            name="video",
            field=models.ImageField(
                blank=True,
                storage=cloudinary_storage.storage.VideoMediaCloudinaryStorage(),
                upload_to="videos/",
                validators=[cloudinary_storage.validators.validate_video],
            ),
        ),
    ]
