# Generated by Django 5.0.7 on 2024-09-10 18:43

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0003_alter_video_featured_image_alter_video_video"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="video",
            field=cloudinary.models.CloudinaryField(
                max_length=255, verbose_name="video"
            ),
        ),
    ]
