# Generated by Django 5.0.7 on 2024-09-12 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0006_section_lesson_section"),
    ]

    operations = [
        migrations.AddField(
            model_name="section",
            name="course",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sections",
                to="courses.course",
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="section",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="lessons",
                to="courses.section",
            ),
        ),
    ]
