# Generated by Django 5.0.7 on 2024-09-16 07:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0007_section_course_alter_lesson_section"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="course",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="coursebundle",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="section",
            options={"ordering": ["order"]},
        ),
        migrations.AlterField(
            model_name="video",
            name="featured_image",
            field=models.URLField(max_length=250),
        ),
        migrations.AlterField(
            model_name="video",
            name="video",
            field=models.URLField(max_length=250),
        ),
    ]
