# Generated by Django 5.0.7 on 2024-09-15 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0008_alter_course_options_alter_coursebundle_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="language",
            field=models.URLField(max_length=50),
        ),
    ]
