# Generated by Django 5.0.7 on 2024-09-16 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0009_alter_course_language"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="language",
            field=models.CharField(max_length=50),
        ),
    ]
