# Generated by Django 5.0.7 on 2024-09-21 17:20

import datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0012_usercourseprogress_userlessoncompletion"),
    ]

    operations = [
        migrations.AddField(
            model_name="coursebundlechoice",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(
                    2024, 9, 21, 17, 19, 53, 464428, tzinfo=datetime.timezone.utc
                ),
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="coursebundlechoice",
            name="enrolled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="coursebundlechoice",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="coursebundlechoice",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
