# Generated by Django 5.0.7 on 2024-09-21 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0013_coursebundlechoice_created_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="coursebundlechoice",
            name="enrolled",
        ),
        migrations.RemoveField(
            model_name="userlessoncompletion",
            name="completed",
        ),
    ]
