# Generated by Django 5.0.7 on 2024-09-21 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0014_remove_coursebundlechoice_enrolled_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserVideoAccess",
        ),
    ]
