# Generated by Django 5.0.7 on 2024-09-22 18:14

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0015_delete_uservideoaccess"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="coursebundlechoice",
            unique_together={("user", "course_bundle")},
        ),
    ]
